[package]
name = "solitaire-two-table"
version = "0.1.0"
authors = ["Spheniscine <spheniscine@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.3", features = [] }
enum-map = "3.1.0"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
rand = "0.10.3"
serde = "1.0.229"
serde_tuple = "1.1.3"
strum = "0.28.0"
strum_macros = "0.28.0"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
