[application]

# `build` & `serve` dist path
platform = "web"

[web]
pre_compress = false

[web.app]
base_path = "solitaire-two-table"

# HTML title tag content
title = "Two-Table Solitaire"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
